# Generated by Django 5.0.1 on 2026-01-22 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_lms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cursorelator',
            name='rol',
        ),
        migrations.AlterField(
            model_name='cursorelator',
            name='especialidad',
            field=models.CharField(blank=True, help_text='Área de especialidad del relator en este curso', max_length=100),
        ),
        migrations.AddIndex(
            model_name='cursorelator',
            index=models.Index(fields=['activo'], name='curso_relat_activo_2578d8_idx'),
        ),
    ]
