# Generated by Django 5.0.1 on 2026-01-26 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_lms', '0002_remove_cursorelator_rol_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='inscripcion',
            index=models.Index(fields=['diploma_codigo_validacion'], name='inscripcion_diploma_eea55f_idx'),
        ),
    ]
