# Generated by Django 5.0.1 on 2026-01-29 18:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_lms', '0003_inscripcion_inscripcion_diploma_eea55f_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacion',
            name='nota_maxima',
            field=models.DecimalField(decimal_places=1, default=7.0, help_text='Nota máxima de la escala (típicamente 7.0)', max_digits=3),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='nota_minima',
            field=models.DecimalField(decimal_places=1, default=1.0, help_text='Nota mínima de la escala (típicamente 1.0)', max_digits=3),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='porcentaje_aprobacion',
            field=models.IntegerField(default=60, help_text='Porcentaje de exigencia para aprobar (típicamente 60%)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='aprobacion_manual',
            field=models.BooleanField(default=False, help_text='True si el admin aprobó/reprobó manualmente (decisión excepcional)'),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='cumple_requisitos_aprobacion',
            field=models.BooleanField(default=False, help_text='True si cumple: nota >= 4.0 Y asistencia >= 75%'),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='fecha_revision',
            field=models.DateTimeField(blank=True, help_text='Fecha en que el admin revisó la inscripción', null=True),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='justificacion_aprobacion',
            field=models.TextField(blank=True, help_text='Justificación del admin para aprobar/reprobar (obligatoria en decisiones excepcionales)'),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='nota_final_calculada',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Nota calculada automáticamente por el sistema (promedio ponderado)', max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(7.0)]),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='revisado_por',
            field=models.ForeignKey(blank=True, help_text='Administrador que revisó y aprobó/reprobó la inscripción', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inscripciones_revisadas', to='api_lms.usuario'),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='peso_porcentaje',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Peso de esta evaluación en la nota final del curso (%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='estado',
            field=models.CharField(choices=[('inscrito', 'Inscrito'), ('en_curso', 'En Curso'), ('completado', 'Completado'), ('pendiente_revision', 'Pendiente de Revisión'), ('aprobado', 'Aprobado'), ('reprobado', 'Reprobado'), ('retirado', 'Retirado'), ('suspendido', 'Suspendido')], default='inscrito', max_length=20),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='nota_final',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Nota final oficial del curso (asignada por admin)', max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(7.0)]),
        ),
        migrations.AddIndex(
            model_name='inscripcion',
            index=models.Index(fields=['cumple_requisitos_aprobacion'], name='inscripcion_cumple__7fee44_idx'),
        ),
        migrations.AddIndex(
            model_name='inscripcion',
            index=models.Index(fields=['revisado_por'], name='inscripcion_revisad_7aa526_idx'),
        ),
    ]
